### ISSUE TITLE
Game crashes when clicking snad in the ingame mods menu

### ISSUE THREAD

**Issue by csumpasd** [lazynessmind/Snad#4]
If you click the snad entry in the ingame mods menu the game crashes. I am using the latest version of forge and snad. It is because of an ArrayIndexOutOfBoundsException related to a mouse click event handler. It is not a big issue, but I hope I could help!

**Comment by lazynessmind** [comment]
Thanks for the help. The issue has been solved and a new build is submitted on [Curse](https://www.curseforge.com/minecraft/mc-mods/snad-back-to-the-past)

**Comment by jacobthefailure** [comment]
The issue is still present in the latest Curse build, and despite the filename being 'snad-1.8.4.22a-1.15.2.jar', it reports ingame as 1.8.3.3a.
